spring.application.name=supervision-api

# Port
server.port=${SERVER_PORT:8080}

# Graceful shutdown
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# Actuator ? expose /actuator/health pour ECS
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# DynamoDB
aws.dynamodb.table-name=${TABLE_NAME:machine_state}
aws.region=${AWS_REGION:eu-west-3}
